authapp/urls.py
from django.urls import path

from authapp.views import login, register, logout, profile, verify

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('logout/', logout, name='logout'),
    path('profile/', profile, name='profile'),
    path('verify/<email>/<key>', verify, name='verify')
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mainapp.views import index, contacts

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('courses/', include('mainapp.urls', namespace='courses')),
    path('users/', include('authapp.urls', namespace='users')),
    path('contacts/', contacts, name='contacts'),
    path('baskets/', include('basketapp.urls', namespace='baskets')),
    path('admin-staff/', include('adminapp.urls', namespace='admin_staff')),
    path('', include('social_django.urls', namespace='social'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

from mainapp.views import courses

app_name = 'mainapp'

urlpatterns = [
    path('', courses, name='index'),
    path('<int:id>/', courses, name='courses'),
]

authapp/models.py
from datetime import timedelta
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.timezone import now


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True)
    activation_key = models.CharField(max_length=128, blank=True)
    activation_key_created = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def is_activation_key_expired(self):
        if now() < self.activation_key_created + timedelta(hours=48):
            return False
        return True


class UserProfile(models.Model):
    MALE = 'M'
    FEMALE = 'W'

    GENDER_CHOICES = (
        (MALE, 'М'),
        (FEMALE, 'Ж')
    )

    user = models.OneToOneField(User, unique=True, null=False, db_index=True, on_delete=models.CASCADE)
    tagline = models.CharField(verbose_name='Тэги', max_length=128, blank=True)
    about_me = models.TextField(verbose_name='О себе', max_length=512, blank=True)
    gender = models.CharField(verbose_name='Пол', choices=GENDER_CHOICES, blank=True, max_length=1)
    birth_date = models.DateField(blank=True, null=True)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            UserProfile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.userprofile.save()

authapp/forms.py
import hashlib
import random
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from authapp.models import User, UserProfile


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'general-form-input', 'placeholder': 'Введите имя пользователя'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'general-form-input', 'placeholder': 'Введите пароль'}))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegisterForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'general-form-input', 'placeholder': 'Введите имя пользователя'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'general-form-input', 'placeholder': 'Введите адрес эл. почты'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'general-form-input', 'placeholder': 'Введите имя'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'general-form-input', 'placeholder': 'Введите фамилию'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'general-form-input', 'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'general-form-input', 'placeholder': 'Подтвердите пароль'}), help_text='Пароль')

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')
        labels = {
            'password2': 'Пароль'
        }

    def save(self):
        user = super().save()
        user.is_active = False
        salt = hashlib.sha1(str(random.random()).encode('utf8')).hexdigest()[:6]
        user.activation_key = hashlib.sha1((user.email + salt).encode('utf8')).hexdigest()
        user.save()

        return user


class UserProfileForm(UserChangeForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'general-form-input general-form-input-read-only', 'readonly': True
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'general-form-input'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'general-form-input'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'general-form-input'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'general-form-input'}), required=False)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'image')


class UserProfileEditForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('tagline', 'about_me', 'gender', 'birth_date')

    tagline = forms.CharField(widget=forms.TextInput(attrs={'class': 'general-form-input'}))
    about_me = forms.CharField(widget=forms.Textarea(attrs={'class': 'general-form-input', 'rows': 5}))
    gender = forms.ChoiceField(
        choices=UserProfile.GENDER_CHOICES,
        widget=forms.Select(attrs={'class': 'general-form-input'})
    )
    birth_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'general-form-input'}))

authapp/views.py
import logging

from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth, messages
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from authapp.forms import UserLoginForm, UserRegisterForm, UserProfileForm, UserProfileEditForm
from authapp.models import User


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user and user.is_active:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('index'))
    else:
        form = UserLoginForm()
    context = {'title': 'GeekShop - Авторизация', 'form': form}
    return render(request, 'authapp/login.html', context)


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            if send_verify_link(user):
                logging.debug('Sent verify link successful')
            else:
                logging.debug('Sent verify link error')
            messages.success(request, 'Вы успешно зарегестрировались!')
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegisterForm()
    context = {'title': 'GeekShop - Регистрация', 'form': form}
    return render(request, 'authapp/register.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(data=request.POST, files=request.FILES, instance=request.user)
        profile_form = UserProfileEditForm(data=request.POST, instance=request.user.userprofile)
        if form.is_valid() and profile_form.is_valid():
            form.save()
            messages.success(request, 'Изменения успешно внесены')
            return HttpResponseRedirect(reverse('users:profile'))
    else:
        form = UserProfileForm(instance=request.user)
        profile_form = UserProfileEditForm(instance=request.user.userprofile)
    context = {
        'title': 'GeekShop - Личный кабинет',
        'form': form,
        'profile_form': profile_form
    }
    return render(request, 'authapp/profile.html', context)


def send_verify_link(user):
    verify_link = reverse('authapp:verify', args=[user.email, user.activation_key])
    subject = 'Подтвердите свой аккаунт'
    message = f'Ссылка для активации вашего профиля на Ramisport: {settings.DOMAIN_NAME}{verify_link}'
    return send_mail(subject, message, settings.EMAIL_HOST_USER, [user.email], fail_silently=False)


def verify(request, email, key):
    user = User.objects.filter(email=email).first()
    if user and user.activation_key == key and not user.is_activation_key_expired():
        user.is_active = True
        user.activation_key = ''
        user.activation_key_created = None
        user.save()
        auth.login(request, user)
    return render(request, 'authapp/verify.html')

authapp/templates/authapp/login.html
{% extends 'mainapp/base.html' %}

{% load static %}

{% block content %}

    <!-- Заголовок страницы -->
    <div class="general-header-banner">
        <h2 class="general-header-banner-title">Авторизация</h2>
    </div>
    <!-- Заголовок страницы -->


    <!-- Контейнер с формой входа-->
    <div class="container">
        <div class="form-page">

            <!-- Ошибки -->
            {% if messages or form.non_field_errors %}
                <div class="form-alert-container
             {% if messages %} form-alert-success {% else %} form-alert-warning {% endif %}" role="alert">
                    <div class="login-form-alert">
                        {% if messages %}
                            {% for message in messages %}
                                <p>{{ message }}</p>
                            {% endfor %}
                        {% else %}
                            {% for error in form.non_field_errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <button type="button" class="form-alert-dismiss-button" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
            <!-- Ошибки -->

            <!-- Форма для входа -->
            <div class="login-form-container">

                <form class="login-form" action="{% url 'users:login' %}" method="post">
                    {% csrf_token %}
                    <div class="general-form-group-vertical">
                        <label class="general-form-label" for="{{ form.username.id_for_label }}">Логин</label>
                        {{ form.username }}
                    </div>
                    <div class="general-form-group-vertical">
                        <label class="general-form-label" for="{{ form.password.id_for_label }}">Пароль</label>
                        {{ form.password }}
                    </div>
                    <div class="general-form-group-vertical">
                        <a class="general-form-label" href="{% url 'social:begin' 'vk-oauth2' %}?next=/">
                            Войти через VK
                        </a>
                        <a class="general-form-label" href="#">Забыли пароль?</a>
                        <input class="general-form-btn" type="submit" value="Авторизоваться">
                    </div>
                </form>
            </div>
            <!-- Форма для входа -->

        </div>
    </div>
    <!-- Контейнер с формой входа-->


{% endblock %}

authapp/templates/authapp/profile.html
{% extends 'mainapp/base.html' %}

{% load static %}

{% block content %}



    <!-- Контейнер с формой входа-->
    <div class="container">
        <div class="form-page">

            {% if messages or form.non_field_errors %}
                <div class="form-alert-container {% if messages %} form-alert-success {% else %} form-alert-warning {% endif %}" role="alert">
                    <div class="profile-form-alert">
                        {% if messages %}
                            {% for message in messages %}
                                <p>{{ message }}</p>
                            {% endfor %}
                        {% else %}
                            {% for error in form.non_field_errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <button type="button" class="form-alert-dismiss-button" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}

            <!-- Форма для изменения профиля -->
            <div class="profile-form-container">

                <form class="profile-form" action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="profile-form-image-container">
                        <img src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'img/profile.png' %} {% endif %}"
                             alt="'profile-image" class="profile-form-image">
                    </div>
                    <div class="profile-form-text-container">
                        <div class="general-form-row">
                            <div class="general-form-group-vertical ">
                                <label class="general-form-label" for="{{ form.first_name.id_for_label }}">Имя</label>
                                {{ form.first_name }}
                            </div>
                            <div class="general-form-group-vertical">
                                <label class="general-form-label" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                {{ form.last_name }}
                            </div>
                        </div>
                        <div class="general-form-row">
                            <div class="general-form-group-vertical">
                                <label class="general-form-label" for="{{ form.username.id_for_label }}">Логин</label>
                                {{ form.username }}
                            </div>
                            <div class="general-form-group-vertical">
                                <label class="general-form-label" for="{{ form.email.id_for_label }}">Адрес электронной
                                    почты</label>
                                {{ form.email }}
                            </div>
                        </div>

                        <div class="general-form-group-vertical">
                            <label class="general-form-label" for="{{ form.image.id_for_label }}">Выбрать изображение</label>
                            {{ form.image }}
                            <label class="general-form-label" for="{{ profile_form.gender.id_for_label }}">Пол</label>
                            {{ profile_form.gender }}
                            <label class="general-form-label" for="{{ profile_form.birth_date.id_for_label }}">Дата рождения</label>
                            {{ profile_form.birth_date }}
                            <label class="general-form-label" for="{{ profile_form.tagline.id_for_label }}">Тэги</label>
                            {{ profile_form.tagline }}
                            <label class="general-form-label" for="{{ profile_form.about_me.id_for_label }}">Обо мне</label>
                            {{ profile_form.about_me }}
                            <input class="general-form-btn" type="submit" value="Изменить аккаунт">
                        </div>


                    </div>
                </form>
            </div>
            <!-- Форма для изменения профиля -->

        </div>
    </div>
    <!-- Контейнер с формой входа-->


{% endblock %}

authapp/templates/authapp/register.html
{% extends 'mainapp/base.html' %}

{% load static %}

{% block content %}

    <!-- Заголовок страницы -->
    <div class="general-header-banner">
        <h2 class="general-header-banner-title">Зарегистрироваться</h2>
    </div>
    <!-- Заголовок страницы -->


    <!-- Контейнер с формой входа-->
    <div class="container">
        <div class="form-page">

            {% if form.errors %}
                <div class="form-alert-container form-alert-warning" role="alert">
                    <div class="register-form-alert">
                        {{ form.errors|escape }}
                    </div>
                    <button type="button" class="form-alert-dismiss-button" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}

            <!-- Форма для входа -->
            <div class="register-form-container">

                <form class="register-form" action="{% url 'users:register' %}" method="post">
                    {% csrf_token %}
                    <div class="general-form-row">
                        <div class="general-form-group-vertical ">
                            <label class="general-form-label" for="{{ form.first_name.id_for_label }}">Имя</label>
                            {{ form.first_name }}
                        </div>
                        <div class="general-form-group-vertical">
                            <label class="general-form-label" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                            {{ form.last_name }}
                        </div>
                    </div>

                    <div class="general-form-group-vertical">
                        <label class="general-form-label" for="{{ form.username.id_for_label }}">Логин</label>
                        {{ form.username }}
                    </div>
                    <div class="general-form-group-vertical">
                        <label class="general-form-label" for="{{ form.email.id_for_label }}">Адрес электронной
                            почты</label>
                        {{ form.email }}
                    </div>
                    <div class="general-form-row">
                        <div class="general-form-group-vertical">
                            <label class="general-form-label" for="{{ form.password1.id_for_label }}">Пароль</label>
                            {{ form.password1 }}
                        </div>
                        <div class="general-form-group-vertical">
                            <label class="general-form-label" for="{{ form.password2.id_for_label }}">Подтверждение пароля</label>
                            {{ form.password2 }}
                        </div>
                    </div>
                    <div class="general-form-group-vertical">
                        <input class="general-form-btn" type="submit" value="Создать аккаунт">
                    </div>
                </form>
            </div>
            <!-- Форма для входа -->

        </div>
    </div>
    <!-- Контейнер с формой входа-->


{% endblock %}

authapp/templates/authapp/verify.html
{% extends 'mainapp/base.html' %}

{% load static %}

{% block content %}

    <!-- Заголовок страницы -->
    <div class="general-header-banner">
        <h2 class="general-header-banner-title">Подтверждение почты</h2>
    </div>
    <!-- Заголовок страницы -->


    <!-- Контейнер с сообщение -->
    <div class="container">
        {% if user.is_authenticated %}
            <h1>Поздравляем</h1>
            <p>Вы успешно зарегистрировались</p>
        {% else %}
            <h1>Что-то пошло не так</h1>
            <p>Проверка аккаунта не удалась</p>
        {% endif %}
        <a href="{%  url 'mainapp:index' %}"></a>
    </div>
    <!-- Контейнер с сообщениями -->


{% endblock %}