adminapp/urls.py
from django.urls import path

from adminapp.views import index, admin_users_read, admin_users_create, admin_users_update, admin_users_remove

app_name = 'adminapp'

urlpatterns = [
    path('', index, name='index'),
    path('admin-users-read/', admin_users_read, name='admin_users_read'),
    path('admin-users-create/', admin_users_create, name='admin_users_create'),
    path('admin-users-update/<int:user_id>/', admin_users_update, name='admin_users_update'),
    path('admin-users-remove/<int:user_id>/', admin_users_remove, name='admin_users_remove'),
]

authapp/urls.py
from django.urls import path

from authapp.views import login, register, logout, profile, verify

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('logout/', logout, name='logout'),
    path('profile/', profile, name='profile'),
    path('verify/<email>/<key>', verify, name='verify')
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mainapp.views import index, contacts

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('courses/', include('mainapp.urls', namespace='courses')),
    path('users/', include('authapp.urls', namespace='users')),
    path('contacts/', contacts, name='contacts'),
    path('baskets/', include('basketapp.urls', namespace='baskets')),
    path('admin-staff/', include('adminapp.urls', namespace='admin_staff')),
    path('', include('social_django.urls', namespace='social'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms

from authapp.forms import UserRegisterForm, UserProfileForm
from authapp.models import User


class UserAdminRegisterForm(UserRegisterForm):
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'general-form-input'}), required=False)

    class Meta:
        model = User
        fields = ('username', 'email', 'image', 'first_name', 'last_name', 'password1', 'password2')


class UserAdminProfileForm(UserProfileForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'general-form-input'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'general-form-input'}))

adminapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import user_passes_test

from authapp.models import User
from adminapp.forms import UserAdminRegisterForm, UserAdminProfileForm


@user_passes_test(lambda u: u.is_superuser)
def index(request):
    return render(request, 'adminapp/index.html')


# CRUD - Create Read Update Delete
@user_passes_test(lambda u: u.is_superuser)
def admin_users_read(request):
    context = {'users': User.objects.all()}
    return render(request, 'adminapp/admin-users-read.html', context)


@user_passes_test(lambda u: u.is_superuser)
def admin_users_create(request):
    if request.method == 'POST':
        form = UserAdminRegisterForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin_staff:admin_users_read'))
    else:
        form = UserAdminRegisterForm()
    context = {'form': form}
    return render(request, 'adminapp/admin-users-create.html', context)


@user_passes_test(lambda u: u.is_superuser)
def admin_users_update(request, user_id):
    selected_user = User.objects.get(id=user_id)
    if request.method == 'POST':
        form = UserAdminProfileForm(data=request.POST, files=request.FILES, instance=selected_user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin_staff:admin_users_read'))
    else:
        form = UserAdminProfileForm(instance=selected_user)
    context = {'form': form, 'selected_user': selected_user}
    return render(request, 'adminapp/admin-users-update-delete.html', context)


@user_passes_test(lambda u: u.is_superuser)
def admin_users_remove(request, user_id):
    user = User.objects.get(id=user_id)
    user.is_active = False
    user.save()
    return HttpResponseRedirect(reverse('admin_staff:admin_users_read'))

adminapp/templates/adminapp/admin-users-create.html
{% extends 'adminapp/base.html' %}

{% load static %}

{% block content %}
    <h1 class="admin-page-heading">
        Изменить пользователя
    </h1>
    <div class="admin-container">

        <form class="register-form" action="{% url 'admin_staff:admin_users_create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="general-form-row">
                <div class="general-form-group-vertical ">
                    <label class="general-form-label" for="{{ form.first_name.id_for_label }}">Имя</label>
                    {{ form.first_name }}
                </div>
                <div class="general-form-group-vertical">
                    <label class="general-form-label" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                    {{ form.last_name }}
                </div>
            </div>

            <div class="general-form-group-vertical">
                <label class="general-form-label" for="{{ form.username.id_for_label }}">Логин</label>
                {{ form.username }}
            </div>
            <div class="general-form-group-vertical">
                <label class="general-form-label" for="{{ form.email.id_for_label }}">Адрес электронной
                    почты</label>
                {{ form.email }}
            </div>
            <div class="general-form-row">
                <div class="general-form-group-vertical">
                    <label class="general-form-label" for="{{ form.password1.id_for_label }}">Пароль</label>
                    {{ form.password1 }}
                </div>
                <div class="general-form-group-vertical">
                    <label class="general-form-label" for="{{ form.password2.id_for_label }}">Подтверждение пароля</label>
                    {{ form.password2 }}
                </div>
            </div>
            <div class="general-form-group-vertical">
                <input class="general-form-btn" type="submit" value="Создать аккаунт">
            </div>
        </form>

    </div>


{% endblock %}

adminapp/templates/adminapp/admin-users-read.html
{% extends 'adminapp/base.html' %}

{% load static %}

{% block content %}

    <h1 class="admin-page-heading">
        Пользователи
    </h1>
    <div class="admin-container">

        <a class="admin-btn" href="{% url 'admin_staff:admin_users_create' %}">
            Создать пользователя
        </a>
        <table class="admin-table" id="dataTable" >
            <thead>
            <tr>
                <th>Имя пользователя</th>
                <th>Имя</th>
                <th>Фамилия</th>
                <th>Адрес эл. почты</th>
                <th>Персонал сайта</th>
                <th>Активный</th>
            </tr>
            </thead>
            <tbody>
            {% for user in users %}
                <tr>
                    <td>
                        <a href="{% url 'admin_staff:admin_users_update' user.id %}">
                            {{ user.username }}
                        </a>
                    </td>
                    <td>{{ user.first_name }}</td>
                    <td>{{ user.last_name }}</td>
                    <td>{{ user.email }}</td>
                    <td class="text-center">
                        {% if user.is_staff %}
                            <i class="fas fa-check-circle"></i>
                        {% else %}
                            <i class="fas fa-times-circle"></i>
                        {% endif %}
                    </td>
                    <td class="text-center">
                        {% if user.is_active %}
                            <i class="fas fa-check-circle"></i>
                        {% else %}
                            <i class="fas fa-times-circle"></i>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

adminapp/templates/adminapp/admin-users-update-delete.html
{% extends 'adminapp/base.html' %}

{% load static %}

{% block content %}
    <h1 class="admin-page-heading">
        Изменить пользователя
    </h1>
    <div class="admin-container">


        <form class="profile-form" action="{% url 'admin_staff:admin_users_update' selected_user.id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="profile-form-image-container">
                <img src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'img/profile.png' %} {% endif %}"
                     alt="'profile-image" class="profile-form-image">
            </div>
            <div class="profile-form-text-container">
                <div class="general-form-row">
                    <div class="general-form-group-vertical ">
                        <label class="general-form-label" for="{{ form.first_name.id_for_label }}">Имя</label>
                        {{ form.first_name }}
                    </div>
                    <div class="general-form-group-vertical">
                        <label class="general-form-label" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                        {{ form.last_name }}
                    </div>
                </div>
                <div class="general-form-row">
                    <div class="general-form-group-vertical">
                        <label class="general-form-label" for="{{ form.username.id_for_label }}">Логин</label>
                        {{ form.username }}
                    </div>
                    <div class="general-form-group-vertical">
                        <label class="general-form-label" for="{{ form.email.id_for_label }}">Адрес электронной
                            почты</label>
                        {{ form.email }}
                    </div>
                </div>

                <div class="general-form-group-vertical">
                    <label class="general-form-label" for="{{ form.image.id_for_label }}">Выбрать изображение</label>
                    {{ form.image }}
                </div>
                <div class="general-form-group-vertical">
                    <div class="general-form-row">
                        <input class="admin-btn" type="submit" value="Сохранить">
                        <a class="admin-btn admin-delete-btn" href="{% url 'admin_staff:admin_users_remove' selected_user.id %}">Удалить</a>
                    </div>
                </div>
            </div>
        </form>
    </div>


{% endblock %}

adminapp/templates/adminapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">

    <!-- Page title -->
    <title>{{ title }}</title>

    <!-- Basic CSS -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/fontawesome/all.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template if any -->
    {% block css %} {% endblock %}

</head>

<body>

<div class="admin-page-container">
    <div class="admin-sidebar">
        <div class="admin-sidebar-items">
            <a class="admin-sidebar-item" href="{% url 'index' %}">На сайт</a>
            <a class="admin-sidebar-item" href="{% url 'authapp:profile' %}">Мой профиль</a>
        </div>
        <p class="admin-sidebar-profile-header">
            Администрирование
        </p>
        <div class="admin-sidebar-items">
            <a class="admin-sidebar-item" href="{% url 'admin_staff:admin_users_read' %}">Пользователи</a>
            <a class="admin-sidebar-item" href="#">Курсы</a>
            <a class="admin-sidebar-item" href="#">Категории курсов</a>
        </div>
    </div>
    <div class="admin-page-content">

        <!-- Page Content -->
        {% block content %} {% endblock %}

        {% block footer %} {% endblock %}
        <!-- Page Content -->

    </div>
</div>




<script src="{% static 'vendor/jquery/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/scripts.js' %}"></script>

</body>

</html>

adminapp/templates/adminapp/index.html
{% extends 'adminapp/base.html' %}

{% load static %}

{% block content %}

    <h1 class="admin-page-heading">
        Администрирование
    </h1>

{% endblock %}