authapp/urls.py
from django.urls import path

from authapp.views import login, register, logout, profile, verify

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('logout/', logout, name='logout'),
    path('profile/', profile, name='profile'),
    path('verify/<email>/<key>', verify, name='verify')
]

basketapp/urls.py
from django.urls import path

from basketapp.views import basket_add, basket_remove, basket_view, basket_edit

app_name = 'basketapp'

urlpatterns = [
    path('add/<int:course_id>/', basket_add, name='basket_add'),
    path('remove/<int:id>/', basket_remove, name='basket_remove'),
    path('basket-view', basket_view, name='basket_view'),
    path('edit/<int:id>/<int:quantity>/', basket_edit, name='basket_edit'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mainapp.views import index, contacts

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('courses/', include('mainapp.urls', namespace='courses')),
    path('users/', include('authapp.urls', namespace='users')),
    path('contacts/', contacts, name='contacts'),
    path('baskets/', include('basketapp.urls', namespace='baskets')),
    path('admin-staff/', include('adminapp.urls', namespace='admin_staff')),
    path('', include('social_django.urls', namespace='social'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

from mainapp.views import courses

app_name = 'mainapp'

urlpatterns = [
    path('', courses, name='index'),
    path('<int:id>/', courses, name='courses'),
]

mainapp/models.py
from django.db import models


class CourseCategory(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = 'Course Categories'

    def __str__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(max_length=256)
    image = models.ImageField(upload_to='course_images', blank=True)
    description = models.CharField(max_length=64, blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    category = models.ForeignKey(CourseCategory, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.category.name} | {self.name}'

mainapp/views.py
from django.shortcuts import render
from mainapp.models import Course, CourseCategory


def index(requests):
    context = {'title': 'Geekshop'}
    return render(requests, 'mainapp/index.html', context)


def courses(requests):
    context = {
        'title': 'GeekShop - Каталог',
        'courses': Course.objects.all(),
        'categories': CourseCategory.objects.all(),
    }
    return render(requests, 'mainapp/courses.html', context)


def contacts(requests):
    context = {'title': 'Geekshop - Контакты'}
    return render(requests, 'mainapp/contacts.html', context)

mainapp/templates/mainapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">

    <!-- Page title -->
    <title>{{ title }}</title>

    <!-- Basic CSS -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!-- Custom styles for this template if any -->
    {% block css %} {% endblock %}

</head>

<body>

<!-- Навигационная панель -->
<div class="container">
    <div class="navbar">
        <ul class="navbar-items">
            <li class="navbar-item"><img class="navbar-logo" src="{% static 'img/logo.png' %}" alt="Rapport E-Learning"></li>
            <li class="navbar-item"><a href="{% url 'index' %}">Главная</a></li>
            <li class="navbar-item"><a href="{% url 'mainapp:index' %}">Каталог</a></li>
        </ul>
        <ul class="navbar-user-profile">
            {% if user.is_superuser %}
                <li class="navbar-item"><a href="{% url 'admin_staff:index' %}">Админка</a></li>
            {% endif %}
            {% if user.is_authenticated %}
                <li class="navbar-item">
                    <a href="{% url 'basketapp:basket_view' %}">
                        Корзина
                        {%  if basket %}
                            {{ basket.0.total_sum|floatformat:0 }} руб ({{ basket.0.total_quantity }} шт.)
                            {%  endif %}
                    </a>
                </li>
                <li class="navbar-item"><a href="{% url 'authapp:profile' %}">{{ user.username }}</a></li>
                <li class="navbar-item"><a href="{% url 'authapp:logout' %}">Выйти</a></li>
            {% else %}
                <li class="navbar-item"><a href="{% url 'authapp:login' %}">Войти</a></li>
                <li class="navbar-item"><a href="{% url 'authapp:register' %}">Зарегистрироваться</a></li>
            {% endif %}
        </ul>
    </div>
</div>
<!-- Навигационная панель -->


<!-- Page Content -->
{% block content %} {% endblock %}

{% block footer %} {% endblock %}
<!-- Page Content -->


<!-- Подвал -->
<div class="footer footer-first-box">
    <div class="container">
        <div class="footer-feedback">
            <div class="footer-feedback-text-box">
                <h3 class="footer-feedback-heading">Есть вопросы?</h3>
                <p class="footer-feedback-text">Напишите нам! Воспользуйтесь формой на сайте или свяжитесь с нами через контакты ниже.</p>
            </div>
            <div class="footer-feedback-button-box">
                <a href="{% url 'contacts' %}" class="footer-feedback-button">Контакты</a>
            </div>
        </div>
    </div>
    <div class="footer">
        <div class="container">
            <div class="footer-contacts">
                <p class="footer-contacts-item">Rapport Online: Rapport E-Learning</p>
                <p class="footer-contacts-item">+79161010100</p>
                <p class="footer-contacts-item">info@raport.ru</p>
            </div>
            <p class="footer-rights-reserved">2021 Все права защищены</p>
        </div>
    </div>
</div>
<!-- Подвал -->

<script src="{% static 'vendor/jquery/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/scripts.js' %}"></script>

</body>

</html>

mainapp/templates/mainapp/catalog.html
{% extends 'mainapp/base.html' %}

{% load static %}

{% block content %}


    <!-- Каталог -->
    <div class="catalog-container">
        <div class="container">
            <div id="catalog">
                {% for course in courses %}
                <div class="catalog-item-card">
                    <img src="{% static '' %}img/courses/{{course.image}}" alt="Что такое сервисный дизайн" class="catalog-item-image">
                    <p class="general-heading-mini">{{ course.title }}</p>
                    <div class="catalog-item-price-and-buy">
                        <p class="catalog-item-price">{{ course.price}} руб.</p>
                        <a class="catalog-item-buy-button" data-item_id="{{ course.id }}">В корзину</a>
                    </div>
                </div>
                {%  endfor %}
            </div>
        </div>
    </div>
    <!-- Каталог -->

{% endblock %}

mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/base.html' %}

{% load static %}

{% block content %}

    <!-- Заголовок страницы контактов -->
    <div class="general-header-banner">
        <h2 class="general-header-banner-title">Напишите нам</h2>
        <p class="contacts-title-comment">Мы всегда открыты к вопросам и предложениями. Наша цель - счастливые клиенты, мы всегда рады обратной связи от вас.</p>
    </div>
    <!-- Заголовок страницы контактов -->


    <!-- Контейнер с контактами и формой связи-->
    <div class="container">
        <div class="contacts-row">

            <!-- Контакты которые слева -->
            <div class="contacts-list-container">
                <img class="contacts-image" src="{% static 'img/contact.png' %}" alt="contact us">
                <div class="contacts-address">
                    <h4 class="contacts-title">Адрес</h4>
                    <p class="contacts-address-text">г. Москва, Пресненская набережная, дом 66</p>
                </div>

                <div class="contacts-address">
                    <h4 class="contacts-title">Телефон</h4>
                    <ul class="contacts-list-items">
                        <li>+79161010100</li>
                        <li>+79161010101</li>
                    </ul>
                </div>

                <div class="contacts-online">
                    <h4  class="contacts-title">Онлайн контакты</h4>
                    <ul class="contacts-list-items">
                        <li><a href="index.html">raport.ru</a></li>
                        <li><a href="mailto:info@elefut.com">info@raport.ru</a></li>
                    </ul>
                </div>
            </div>
            <!-- Контакты которые слева -->

            <!-- Форма для связи которая справа -->
            <div class="contact-form-container">
                <p class="contact-form-title">Сообщение</p>
                <form class="contact-form" action="#">
                    <div class="general-form-group-vertical">
                        <label class="general-form-label" for="name">Имя</label>
                        <input id="name" class="general-form-input" type="text" placeholder="Ваше имя">
                    </div>
                    <div class="general-form-group-vertical">
                        <label class="general-form-label" for="email">Email</label>
                        <input id="email" class="general-form-input" type="email" placeholder="Ваш email">
                    </div>
                    <div class="general-form-group-vertical">
                        <label class="general-form-label" for="message">Сообщение</label>
                        <textarea id="message" class="general-form-input" placeholder="Ваше сообщение" rows="5"></textarea>
                    </div>
                    <button class="general-form-btn" type="submit">Отправить</button>
                </form>
            </div>
            <!-- Форма для связи которая справа -->

        </div>
    </div>
    <!-- Контейнер с контактами и формой связи-->


    <!-- Виджет с картой -->
    <div class="container">


        <div class="contacts-map">
            <div style="position:relative;overflow:hidden;">
                <a href="https://yandex.ru/maps/213/moscow/?utm_medium=mapframe&utm_source=maps" style="color:#eee;font-size:12px;position:absolute;top:0px;">Москва</a>
                <a href="https://yandex.ru/maps/213/moscow/house/1_y_krasnogvardeyskiy_proyezd_11/Z04YcwNgQUUFQFtvfXt0cXRrYA==/?ll=37.542023%2C55.748919&utm_medium=mapframe&utm_source=maps&z=16.2" style="color:#eee;font-size:12px;position:absolute;top:14px;">1-й Красногвардейский проезд, 11 — Яндекс.Карты</a>
                <iframe src="https://yandex.ru/map-widget/v1/-/CCUMnJw6oC" width="100%" height="480" frameborder="1" allowfullscreen="true" style="position:relative;"></iframe>
            </div>
        </div>
    </div>
    <!-- Виджет с картой -->


{% endblock %}

mainapp/templates/mainapp/courses.html
{% extends 'mainapp/base.html' %}

{% load static %}
{% load humanize %}

{% block content %}


    <!-- Каталог -->
    <div class="catalog-container">
        <div class="container">
            <div id="catalog">
                {% for course in courses %}
                <div class="catalog-item-card">
                    <img src="/media/{{course.image}}" alt="Что такое сервисный дизайн" class="catalog-item-image">
                    <p class="general-heading-mini">{{ course.name }}</p>
                    <div class="catalog-item-price-and-buy">
                        <p class="catalog-item-price">{{ course.price|floatformat:"0"|intcomma}} руб.</p>
                        <a class="catalog-item-buy-button" href="{% url 'baskets:basket_add' course.id %}">В корзину</a>
                    </div>
                </div>
                {%  endfor %}
            </div>
        </div>
    </div>
    <!-- Каталог -->

{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}

{% load static %}

{% block content %}

    <!-- Лэндинг -->
    <div class="landing-top">

        <!-- Встречающий текст -->
        <div class="landing-top-text container ">
            <h1 class="landing-top-text-primary">Онлайн-курсы будущего</h1>
            <p class="general-text landing-top-text-secondary">Начните учиться прямо сейчас! Более 100 онлайн-курсов по компетенциям и навыкам будущего.</p>
            <a href="#" class="landing-top-button">Перейти в каталог</a>
        </div>
        <!-- Встречающий текст -->

    </div>
    <!-- Лэндинг -->


    <!-- Второй контейнер - темы курсов -->
    <div class="topics-we-teach container">
        <h3 class="topics-cards-title general-heading">Главные темы на {% now "d.m.Y" %}</h3>
        <div class="topics-cards-box">
            <div class="topic-card">
                <img class="topic-card-img" src="{% static 'img/topic-card-1.svg' %}" alt="Transformation">
                <h4 class="general-heading-mini">Цифровая трансформация</h4>
                <p class="general-text">Узнайте что дает цифровая трансформация и как управлять управлять изменениями бизнеса</p>
                <a href="#" class="topic-card-link">Подробнее</a>
            </div>

            <div class="topic-card">
                <img class="topic-card-img" src="{% static 'img/topic-card-2.svg' %}" alt="Development">
                <h4 class="general-heading-mini">Разработка цифровых продуктов</h4>
                <p class="general-text">Узнайте как запустить цифровой продукт для внутреннего или внешнего клиента</p>
                <a href="#" class="topic-card-link">Подробнее</a>
            </div>

            <div class="topic-card">
                <img class="topic-card-img" src="{% static 'img/topic-card-3.svg' %}" alt="Design">
                <h4 class="general-heading-mini">Сервисный дизайн</h4>
                <p class="general-text">Узнайте как разрабатывать сервисы, которые буду приносить прибыль вам и счастье клиентам</p>
                <a href="#" class="topic-card-link">Подробнее</a>
            </div>
        </div>
    </div>
    <!-- Второй контейнер - темы курсов -->


    <!-- Текст для контейнера с популярными курсами -->
    <div class="featured-courses container">
        <h3 class="general-heading">Популярные курсы</h3>
        <p class="featured-courses-text">Найдите программу обучения, подходящую вам. Большой курс или интенсив на пару часов? Выбор за вами.</p>
        <div class="featured-courses-item">
            <img src="{% static 'img/course-img-1.png' %}" alt="Course" class="featured-courses-img">
            <p class="featured-courses-title">Интернет вещей: Введение</p>
        </div>
        <div class="featured-courses-group">
            <div class="featured-courses-item featured-courses-item-margin">
                <img src="{% static 'img/course-img-2.png' %}" alt="Course" class="featured-courses-img">
                <p class="featured-courses-title">Проектирование мобильного приложения</p>
            </div>
            <div class="featured-courses-item">
                <img src="{% static 'img/course-img-3.png' %}" alt="Course" class="featured-courses-img">
                <p class="featured-courses-title">Внедрение BI систем</p>
            </div>
        </div>
    </div>
    <!-- Текст для контейнера с популярными курсами -->

{% endblock %}