authapp/urls.py
from django.urls import path

from authapp.views import login, register, logout, profile, verify

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('logout/', logout, name='logout'),
    path('profile/', profile, name='profile'),
    path('verify/<email>/<key>', verify, name='verify')
]

basketapp/urls.py
from django.urls import path

from basketapp.views import basket_add, basket_remove, basket_view, basket_edit

app_name = 'basketapp'

urlpatterns = [
    path('add/<int:course_id>/', basket_add, name='basket_add'),
    path('remove/<int:id>/', basket_remove, name='basket_remove'),
    path('basket-view', basket_view, name='basket_view'),
    path('edit/<int:id>/<int:quantity>/', basket_edit, name='basket_edit'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mainapp.views import index, contacts

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('courses/', include('mainapp.urls', namespace='courses')),
    path('users/', include('authapp.urls', namespace='users')),
    path('contacts/', contacts, name='contacts'),
    path('baskets/', include('basketapp.urls', namespace='baskets')),
    path('admin-staff/', include('adminapp.urls', namespace='admin_staff')),
    path('', include('social_django.urls', namespace='social'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

from mainapp.views import courses

app_name = 'mainapp'

urlpatterns = [
    path('', courses, name='index'),
    path('<int:id>/', courses, name='courses'),
]

basketapp/models.py
from django.db import models

from authapp.models import User
from mainapp.models import Course


class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Корзина для {self.user.username} | Продукт {self.course.name}'

    def sum(self):
        return self.quantity * self.course.price

    def total_quantity(self):
        baskets = Basket.objects.filter(user=self.user)
        return sum(basket.quantity for basket in baskets)

    def total_sum(self):
        baskets = Basket.objects.filter(user=self.user)
        return sum(basket.sum() for basket in baskets)

basketapp/views.py
from django.shortcuts import HttpResponseRedirect, render
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from mainapp.models import Course
from basketapp.models import Basket


@login_required
def basket_add(request, course_id=None):
    course = Course.objects.get(id=course_id)
    baskets = Basket.objects.filter(user=request.user, course=course)

    if not baskets.exists():
        Basket.objects.create(user=request.user, course=course, quantity=1)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_remove(request, id):
    Basket.objects.get(id=id).delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_view(requests):
    basket = Basket.objects.filter(user=requests.user)
    context = {
        'title': 'GeekShop - Корзина',
        'baskets': basket,
    }
    return render(requests, 'basketapp/basket-view.html', context)


def basket_edit(request, id, quantity):
    if request.is_ajax():
        basket = Basket.objects.get(id=id)
        if quantity > 0:
            basket.quantity = quantity
            basket.save()
        else:
            basket.delete()
        baskets = Basket.objects.filter(user=request.user)
        context = {'baskets': baskets}
        result = render_to_string('basketapp/basket.html', context)
        return JsonResponse({'result': result})

basketapp/templates/basket/basket-view.html
{% extends 'mainapp/base.html' %}

{% load static %}
{% load humanize %}

{% block content %}


    <!-- Каталог -->
    <div class="catalog-container">
        <div class="container">
            {% include 'basket/basket.html' %}
        </div>
    </div>
    <!-- Каталог -->

{% endblock %}

basketapp/templates/basket/basket.html
{% load static %}
{% load humanize %}

<div class="basket-container">
    {% if baskets %}

        {% for basket_item in baskets %}
            <div class="basket-item-row">
                <img src=" {{ basket_item.course.image.url }}" class="basket-item-image" alt="">
                <div class="basket-item-name">{{ basket_item.course.name }}</div>
                <div class="basket-item-price">{{ basket_item.course.price|floatformat:"0"|intcomma }}</div>
                <a class="basket-item-remove" href="{% url 'baskets:basket_remove' basket_item.id %}">
                    Удалить
                </a>
            </div>
        {% endfor %}
        <div class="basket-summary-row">
            <p>В корзине <span>{{ basket_count }}</span> товаров на сумму <span>{{ basket_sum|floatformat:"0"|intcomma }}</span> рублей.</p>
            <a href="#" class="general-btn">Оформить заказ</a>
        </div>

    {% else %}
        <div class="basket-empty-row">
            <p class="general-text">Корзина пока пуста. Давайте <a href="{% url 'mainapp:index' %}">начнем покупки</a>?</p>

        </div>
    {% endif %}
</div>